### ISSUE TITLE
Action Editor for 4k games

### ISSUE THREAD

**Issue by codeDudeRed** [kyouryuukunn/renpy-ActionEditor3#16]
Hi there,

Are there any plans to update code in order to support 4k games(by that I mean enlarging and repositioning textbuttons, bars etc.)

Thanks in advance for your answer.
![image](https://user-images.githubusercontent.com/102157962/222397402-0f352cf2-c78b-4bdc-bb15-e96fa6079c8a.png)

**Comment by kyouryuukunn** [comment]
text style is changeable by new_action_editor_text style.

```

init:
    style new_action_editor_text:
        size 10

```

**Comment by kyouryuukunn** [comment]
I don't have the plan to support 4k by default.
Users need to define styles if it is needed.
