### ISSUE TITLE
Having no camera causes error when opening editor

### ISSUE THREAD

**Issue by a-soulspark** [kyouryuukunn/renpy-ActionEditor3#17]
- **Version:** Ren'Py 8.0.3
- **ActionEditor:** beta_230122

Apparently, if your game doesn't have a camera set up with perspective, ActionEditor crashes when you try opening it (Shift+P):

```md
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script
    m "You are in your room. It's 1am."
  File "game/ActionEditor.rpy", line 2536, in open_action_editor
    action_editor_init()
  File "game/ActionEditor.rpy", line 164, in action_editor_init
    pos = renpy.get_placement(d)
AttributeError: 'NoneType' object has no attribute 'get_placement'
```

I proceeded to add the following lines to the beginning of my script.rpy:
```py
camera:
  perspective True
```
and the error was fixed, because `d` (the camera transform variable) was no longer NoneType.

Perhaps it should be clearer that a camera is required for ActionEditor to function, or create a default camera if one is not present?

**Comment by kyouryuukunn** [comment]
I fixed beta_230311 https://github.com/kyouryuukunn/renpy-ActionEditor3/releases/tag/beta_230311
Fixed crash when perspective is False or None.
