### ISSUE TITLE
Parsing fails after adding ActionEditor3 to FRESHLY created Ren'Py 8.1.0 project

### ISSUE THREAD

**Issue by ExhibitionAmbitions** [kyouryuukunn/renpy-ActionEditor3#21]
I have made no changes to the project, it is just the default Ren'Py 8.1.0 project. I get this error: 
```
[code]
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


File "game/ActionEditor_screens.rpy", line 134: keyword argument 'align' is incompatible with 'pos'.
    align (1., 1.)
         ^

Ren'Py Version: Ren'Py 8.1.0.23051307
Sat May 27 14:17:36 2023
[/code]


```

same issue happens in a new Ren'Py 7.6.0 project.
I am able to use the original [Action Editor](https://github.com/kyouryuukunn/renpy-ActionEditor) and it works, but i really want the 3D camera.

**Comment by kyouryuukunn** [comment]
Thank you. I fixed it.
https://github.com/kyouryuukunn/renpy-ActionEditor3/releases/tag/beta_230528
