### ISSUE TITLE
Crash when "Expression Statement" is set with a "with"

### ISSUE THREAD

**Issue by Waffle631** [kyouryuukunn/renpy-ActionEditor3#22]
I updated the editor version from [231216](https://github.com/kyouryuukunn/renpy-ActionEditor3/releases/tag/231216) to the latest available and it happens that when I display an image, for example:
```
show bg006 00:
        subpixel True ypos -880 zoom 1.3 
        Null(1505.0, 2277.0)
        'bg006 00' with dissolve
```
and open the editor the project stops responding, but if I declare the same image without the `with dissolve` the editor opens without problems.
I tried it in a new project but it still happens.

**Comment by kyouryuukunn** [comment]
I fixed.
