### ISSUE TITLE
Editor does not reflect what appears in game

### ISSUE THREAD

**Issue by ezrablake911** [kyouryuukunn/renpy-ActionEditor3#24]
I've encountered an issue with the Action Editor extension where elements appear to be misaligned. I've observed this behavior in both my main project, a blank project with only the Action Editor extension, and in Tutorial, so I believe the issue lies within the extension itself.

**Expected Behavior:**
When using the Action Editor, the movements we make in the editor should be the same as the movements in the game, once the clipboard data is pasted.

**Actual Behavior:**
Elements appear misaligned. The pasted ATL creates movements which place the elements off screen, zoom them in, etc. It's probably easier to tell what's going on if you reproduce it.

Steps to Reproduce:

-Install the latest version of renpy (8.1.1)
-Install the latest version of Action Editor in the 'tutorial' project.
-Launch the game, and use Action Editor to create movements. I placed Eileen off screen left and raised, then moved her to true center.
-Click 'clipboard' to copy the code, and paste it into the script
-Observe the misalignment of elements.

Additional Information:

    Operating System: Mac OS

Thank you for your time and for providing this extension to the community. I appreciate any assistance you can offer!

**Comment by kyouryuukunn** [comment]
That issue wasn't reproduced.

use Ren'Py 8.1.1.23060707 & ActionEditor beta_230819(https://github.com/kyouryuukunn/renpy-ActionEditor3/releases/tag/beta_230819)

1.  Install Action Editor in the 'tutorial' project.
2.  Launch the game, and open Action Editor. I change Eileen xpos from 0.5 to -0.1 at time 0s then change that to 0.5 at 1s.
3.  Click 'clipboard' to copy the code, and paste it into the script. The result is below.

        # The game starts here.
        #begin start
        label start:
        #end start
    
            scene bg washington
            show eileen vhappy
            with dissolve
    
            # Start the background music playing.
            play music "sunflower-slow-drag.ogg"
    
            window show
    
            e "Hi! My name is Eileen, and I'd like to welcome you to the Ren'Py tutorial."
    
            window hide
            show eileen vhappy:
                subpixel True 
                xpos -0.1 
                linear 1.00 xpos 0.5 
            with Pause(1.10)
            show eileen vhappy:
                xpos 0.5 
            window show
    
            e "In this tutorial, we'll teach you the basics of Ren'Py, so you can make games of your own. We'll also demonstrate many features, so you can see what Ren'Py is capable of."

sample movie
https://www.dropbox.com/s/b21ue05etlpqpx3/ActionEditor_.avi?dl=0

**Comment by ezrablake911** [comment]
My version of action editor produces the exact same code yours produced. I've tried that code in both Windows and Mac versions of renpy 8.1.1.23060707, with and without action editor, and it always produces a transform which puts Eileen slightly to the right of the x center. 

Changing xanchor to 0.5 fixes the issue and makes her behave as expected, putting her at true center. I think actioneditor may be producing ATL which assumes that the anchor defaults to (0.5, 0.0), when in RenPy the anchor actually defaults to (0.0, 0.0)?

Regardless, I can make it work by just manually changing the anchor, but that's potentially something to investigate! Thanks again for your time.

**Comment by kyouryuukunn** [comment]
The only changes from where ActionEditor is opened is included in clipboard.

"show eileen vhappy" shows eileen with xanchor 0.5. So, xanchor 0.5 isn't included explicitly in clipboard if ActionEditor is opened after "show eileen vhappy".

Eileen is shown with xanchor 0 if "show eileen vhappy" is overwritten by clipboard.

**Comment by kyouryuukunn** [comment]
Let's add images in ActionEditor or fix clipboard code manually if you want to show new images.
