### ISSUE TITLE
ActionEditor takes a config.layers that isn't a string and crashes.

### ISSUE THREAD

**Issue by paxogre** [kyouryuukunn/renpy-ActionEditor3#40]
Found this somewhat by accident and stupidity but thought it was funny.

define config.layers = [ 'master', 'transient', 'screens', 'overlay', ... ]
https://www.renpy.org/doc/html/config.html#var-config.layers

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/renpy-ActionEditor3-master/ActionEditor.rpy", line 2975, in open_action_editor
    change_time(0)
  File "game/renpy-ActionEditor3-master/ActionEditor.rpy", line 2854, in change_time
    play(False)
  File "game/renpy-ActionEditor3-master/ActionEditor.rpy", line 1038, in play
    renpy.show("action_preview_"+layer, what=Transform(function=renpy.curry(viewer_transform)(
TypeError: can only concatenate str (not "ellipsis") to str

To fix this
ActionEditor.rpy
```
    def get_layers():
        r = []
        for l in config.layers:
            if isinstance(l, str):
                if l not in not_included_layer:
                    r.append(l)
        return r
```

**Comment by kyouryuukunn** [comment]
Under what circumstances was a non-string assigned to config.layer?

**Comment by paxogre** [comment]
Someone new to coding just copy pasted from the tutorial on how to add layers and didn't remove the ellipsis (...).

Ren'Py doesn't warn that this is a problem with config.layers, and the error log makes it sound like it's a problem with Action Editor which it isn't.  Adding a little filter was an easy fix so while it may be a problem it's not a problem with the code.

Really it just handles a PEBKAC error.
