### ISSUE TITLE
Position will reset with interaction when using the `atl_wiggle()` function in the camera block

### ISSUE THREAD

**Issue by codeforker654** [kyouryuukunn/renpy-ActionEditor3#41]
I do thing like this:
```
    camera:
        function atl_swiggle(deviation=40, fast_forward=3)
```

But every time the dialogue progresses, `atl_wiggle()` function resets the position.

**Comment by kyouryuukunn** [comment]
Change the code like this.

    init python:
            test = atl_swiggle(deviation=40, fast_forward=3)

    camera:
        function test
