### ISSUE TITLE
side views not work

### ISSUE THREAD

**Issue by Art4DD** [kyouryuukunn/renpy-ActionEditor3#7]
Hi, I downloaded the latest build and I don't have "side views", and rotateY rotates incorrectly.
Renpy 8.0.3
[Screenshot](http://joxi.ru/krDqgyaUGNvMgm.png)

**Comment by kyouryuukunn** [comment]
Is perspective False?
side view and other 3d functions depends on perspective value.

**Comment by Art4DD** [comment]
Thanks. I didn't know I needed to turn on perspective. The problem is solved.
