### ISSUE TITLE
3D View?

### ISSUE THREAD

**Issue by MadServlet** [kyouryuukunn/renpy-ActionEditor3#9]
I was checking the changes for the 3D layer feature for ActionEditor3 but the wiki doesn't seem to include it anymore.
Was this feature removed?

**Comment by kyouryuukunn** [comment]
Yes. actioneditor3 doesn't support 3d layer no more.
3d stage is alternative.

**Comment by MadServlet** [comment]
ah alright, can you point me to some documentations on how to use 3D stage?

**Comment by kyouryuukunn** [comment]
https://www.renpy.org/doc/html/3dstage.html

**Comment by MadServlet** [comment]
Thank you!
